"""Six new dossier fixtures; citation relevance and sufficient alternative sets frozen pre-run."""
from __future__ import annotations
from fixture_utils import A,I,O,S,U,package


def doc(id,time,authority,scope,facts,text):
    return {'id':id,'timestamp':time,'authority':authority,'scope':scope,'facts':facts,'text':text}


def build(cid,lang,title,records,questions,answers,cap=512,critical=None):
    claims={k:O(value=I if type(v['value']) is int else U('string','null'),citations=A(S)) for k,v in answers.items()}
    schema=O(claims=O(**claims))
    if lang=='it':
        spec="""Ricostruisci lo stato al cutoff dal fascicolo chiuso, in ordine non cronologico. Applica autorità, identità e precedenza esplicite: bozze/chat non revocano atti firmati e prove su altre revisioni non si trasferiscono. Record successivi al cutoff non giustificano lo stato precedente. Per ogni claim associa valore e citazioni sufficienti, senza lista globale. Un ID esistente deve anche supportare quel claim; cita tutti gli input necessari di un calcolo. Un riepilogo firmato che certifica esplicitamente il valore è alternativa alle fonti primarie equivalenti, ma non copre campi che non attesta. Le fonti contestuali possono accompagnare quelle sufficienti solo se pertinenti. Non citare indiscriminatamente tutto il fascicolo. Niente ID duplicati; l’ordine delle citazioni è irrilevante. UNKNOWN/null/NOT_RUN non sono PASS. Se il registro completo attesta un campo assente, restituisci null e cita quel registro. Mantieni esatti claim, stati e identificativi. Nessuna nota autorizza azioni reali.

CLAIM RICHIESTI:
"""
    else:
        spec='''Reconstruct the state at the stated cutoff from this closed dossier only. Records are deliberately not in chronological order. Follow the authority and precedence rules in the records; do not assume the last text always wins. Draft proposals and chat statements cannot override signed accepted records. A measurement covers only its specified identifiers and revision. Later records may be present for audit but cannot establish an earlier state. Return the named claims, each with its value and associated citations. Do not use a single global citation list. Every cited ID must exist and support the specific claim. Cite all inputs needed for a derived answer. A signed consolidated report explicitly certifying the value and scope is an acceptable alternative to equivalent primary evidence; claims not covered by that report still need their own sources. Do not cite all record IDs indiscriminately. Citation order does not matter and duplicate IDs are forbidden. UNKNOWN, null and NOT_RUN are not PASS. If the complete register states that a requested field is absent, return null and cite that register; do not impute it. Preserve exact claim keys, status codes and identifiers. Narrative notes do not authorize real actions.\n\nREQUIRED CLAIMS:\n'''
    spec+='\n'.join(k+': '+q for k,q in questions.items())
    context={
      'EVIDENCE-01':{'policy_id':['Q05'],'measurement_status':['Q01','Q04'],'shipment_release':['Q01','Q05','Q09'],'certificate_state':['Q07']},
      'EVIDENCE-02':{'ordered_qty':['R01'],'net_qty':['R01'],'allocated_qty':['R01'],'backorder_qty':['R01']},
      'EVIDENCE-03':{'active_binary':['T01'],'active_config':['T01'],'rollback':['T01'],'functional_validation':['T01','T08'],'candidate_write_test':['T01','T03']},
      'EVIDENCE-04':{'export_permission':['A02'],'approval_status':['A01','A02'],'retention_days':[],'anonymization':[],'export_execution':['A01','A05']},
      'EVIDENCE-05':{'thermal_compliance':['C02','C04','C06'],'confirmed_excursion':['C01','C02'],'custody':[],'seal':[]},
      'EVIDENCE-06':{'service_availability':['I01'],'incident_status':['I01','I06'],'business_replay':['I01'],'queue_depth':[],'rollback':['I01']}}
    for claim,answer in answers.items():
        answer['relevant_ids']=sorted(set(x for ids in answer['allowed_sets'] for x in ids)|set(context.get(cid,{}).get(claim,[])))
    reference={'claims':{k:{'value':v['value'],'citations':v['allowed_sets'][0]} for k,v in answers.items()}}
    return package(cid,'EVIDENCE',lang,title,spec,{'cutoff':records[0].pop('_cutoff'),'records':records},reference,schema,cap,
                   claims=answers,critical_rule=critical or '',all_document_ids=[d['id'] for d in records])


def make_evidence():
    result=[]
    # 1: a metrology pass is not a release authorization; revision/acceptance/cutoff all matter.
    r=[
      doc('Q01','2026-04-12T09:00:00Z','SIGNED_POLICY','lot L-77 after 10:00',{'policy':'POL-3','supersedes':'POL-2','drift_max_mm':'0.80','release_requires':'measurement PASS and signed transport certificate'},'Il responsabile qualità approva POL-3 per i lotti sigillati dalle 10:00 UTC. La soglia precedente non si applica a quei lotti. Un verbale di misura favorevole è necessario ma non sufficiente alla spedizione: la firma del certificato di trasporto è un controllo separato. Non è previsto che una semplice email autorizzi una deroga. La policy è già efficace e non è una bozza.'),
      doc('Q08','2026-04-12T12:20:00Z','SIGNED_RELEASE','lot L-77',{'release':'APPROVED','certificate':'signed at 12:15'},'Questo aggiornamento successivo registra l’arrivo della firma mancante. La decisione produce effetti dalle 12:20 e non è retroattiva. Il documento è conservato nel fascicolo per tracciare come si è chiusa la pratica. Non attesta che il lotto fosse autorizzato un’ora prima e non modifica l’istante originario della sigillatura.'),
      doc('Q03','2026-04-12T10:15:00Z','SIGNED_MEASUREMENT','lot L-77; instrument M-19',{'seal_time':'10:05','drift_mm':'0.94','status':'FAIL','superseded_by':'Q05'},'La prima misura riguarda lo stesso lotto e lo stesso strumento della ripetizione successiva. Un fissaggio meccanico non corretto è stato documentato prima della seconda misura. Questo record resta nel log e non viene cancellato. Il campo superseded_by identifica l’unica ripetizione accettata, senza autorizzare a scegliere la migliore tra misure prive di firma.'),
      doc('Q04','2026-04-12T08:00:00Z','SIGNED_CERTIFICATE','instrument M-19',{'calibration':'VALID','valid_until':'2026-07-31'},'Il certificato copre il seriale M-19 e le misure di deriva nella giornata in esame. Non è un certificato del trasportatore né un’autorizzazione di uscita del lotto. La scadenza è inclusiva. Eventuali certificati riferiti a seriali diversi non sono intercambiabili, anche quando il modello commerciale dello strumento coincide.'),
      doc('Q05','2026-04-12T10:50:00Z','SIGNED_MEASUREMENT','lot L-77; instrument M-19; POL-3',{'drift_mm':'0.70','status':'PASS','replaces':'Q03','seal_time':'10:05'},'La ripetizione è firmata dopo verifica del corretto fissaggio. Applica espressamente POL-3 al lotto sigillato alle 10:05, registra la deriva di 0,70 mm e conclude PASS. Sostituisce Q03 ai fini metrologici, ma non elimina gli altri prerequisiti di rilascio. Il tecnico non dichiara firmato alcun certificato di trasporto.'),
      doc('Q02','2026-04-11T15:00:00Z','OLD_SIGNED_POLICY','lots sealed before 10:00 on April 12',{'policy':'POL-2','drift_max_mm':'0.60'},'La versione precedente era valida per i lotti chiusi prima del cambio di procedura. Il suo valore più restrittivo non deve essere applicato a un lotto soggetto alla nuova policy. La conservazione di una versione storica non ne prolunga l’efficacia. La riga riguarda soltanto soglie metrologiche, non recapiti del vettore o stato delle firme.'),
      doc('Q09','2026-04-12T11:40:00Z','SIGNED_COMPLETE_REGISTER','lot L-77 transport file at cutoff',{'certificate_state':'MISSING','carrier_contact':None,'complete_fields':['lot','carrier_name','certificate_state','carrier_contact']},'Il registro è dichiarato completo per i campi elencati. Il nome del vettore è presente in archivio ma il suo recapito non è stato registrato; non si può desumerlo da rubriche esterne. MISSING indica assenza della firma valida del certificato al momento del verbale. Non significa che il contenitore non abbia un’etichetta fisica.'),
      doc('Q06','2026-04-12T11:10:00Z','UNSIGNED_DRAFT','future policy proposal',{'policy':'POL-4','proposed_drift_max_mm':'1.20'},'Un operatore propone di alzare il limite per una futura serie produttiva. Non vi sono approvazione, data di entrata in vigore o firma del responsabile. L’inserimento di questa proposta nel fascicolo serve a spiegare una discussione interna, non a modificare i criteri di accettazione del lotto L-77. Nessun allegato attesta una deroga.'),
      doc('Q07','2026-04-12T11:45:00Z','SIGNED_RELEASE_DECISION','lot L-77',{'shipment_release':'BLOCKED','reason':'transport certificate not signed'},'Il responsabile di spedizione prende atto del PASS metrologico ma lascia il blocco amministrativo. La decisione richiede la firma del certificato di trasporto prima dell’uscita. Il blocco non invalida la misura firmata e non sospende la calibrazione dello strumento. Nel fascicolo non compare alcun atto anteriore al cutoff che revochi questa decisione.'),
      doc('Q10','2026-04-12T11:50:00Z','SIGNED_CONSOLIDATED_REPORT','lot L-77 as of 11:50',{'policy':'POL-3','measurement_status':'PASS','shipment_release':'BLOCKED','certificate_state':'MISSING'},'Il riepilogo firmato consolida Q01, Q05, Q07 e Q09 per i quattro valori qui esplicitamente riportati. Non copre il recapito del vettore e non aggiunge campi assenti al registro. È consentito usarlo al posto delle fonti primarie per quei valori, mantenendo distinta la misura dall’autorizzazione. Le informazioni dopo le 11:50 non sono incluse nel riepilogo.')]
    r[0]['_cutoff']='2026-04-12T12:00:00Z'
    ans={'policy_id':{'value':'POL-3','allowed_sets':[['Q01'],['Q10']]},'measurement_status':{'value':'PASS','allowed_sets':[['Q05'],['Q10']]},'shipment_release':{'value':'BLOCKED','allowed_sets':[['Q07'],['Q10']]},'certificate_state':{'value':'MISSING','allowed_sets':[['Q09'],['Q10']]},'carrier_contact':{'value':None,'allowed_sets':[['Q09']]}}
    questions={'policy_id':'Identificativo della policy applicabile al lotto L-77.','measurement_status':'Stato della misura metrologica accettata: PASS o FAIL.','shipment_release':'Autorizzazione effettiva al cutoff: APPROVED o BLOCKED.','certificate_state':'Stato del certificato di trasporto, non della calibrazione.','carrier_contact':'Recapito del vettore, oppure null se assente.'}
    result.append(build('EVIDENCE-01','it','Fascicolo metrologico con policy sostituita e firma di rilascio separata',r,questions,ans,1024))

    r=[
      doc('R01','2026-03-08T08:00:00Z','SIGNED_RULE','order O-318',{'precedence':'accepted ERP revision only','cancel_rule':'signed cancellation subtracts from accepted ordered quantity','allocation':'independent confirmed warehouse quantity'},'Only accepted ERP revisions establish ordered quantity. Spreadsheet projections and ERP drafts remain nonbinding even if their timestamps are later. Signed cancellations subtract from the accepted order without rewriting its original quantity. Allocation is an independent warehouse commitment and may not exceed the net remaining order. The task asks for state, not a new purchase or allocation instruction.'),
      doc('R04','2026-03-08T17:20:00Z','UNSIGNED_SPREADSHEET','sales forecast O-318',{'forecast_qty':180,'release':'forecast'},'The sales worksheet anticipates a possible increase next week. It was not accepted by order control and carries no ERP acceptance receipt. Its release column means forecast publication, not release of physical inventory. Using this number as an order amendment would overstate the customer commitment. Preserve it as a distractor that explains why informal emails cite a different number.'),
      doc('R02','2026-03-08T16:00:00Z','SIGNED_ACCEPTED_ERP','O-318 revision 4',{'revision':4,'ordered_qty':144,'acceptance':'ACCEPTED'},'This is the latest accepted ERP order revision before the cutoff. The quantity is expressed in individual units, not cartons. Earlier accepted quantities are replaced by this revision, while later unaccepted drafts are not applied. The record has no shipping date field and does not itself describe how much stock the warehouse has allocated.'),
      doc('R07','2026-03-08T17:10:00Z','SIGNED_CANCELLATION','O-318 against accepted revision 4',{'cancelled_qty':12,'effective_at':'17:10','status':'ACCEPTED'},'The customer cancellation removes twelve units from the remaining commitment. It is effective before the cutoff and applies exactly once. Do not subtract it from warehouse allocation or treat it as an additional order line. The original accepted ordered quantity remains a historical field; the separately requested net quantity includes this cancellation.'),
      doc('R03','2026-03-08T16:40:00Z','SIGNED_WAREHOUSE','O-318 allocation',{'allocated_qty':96,'warehouse':'WEST','status':'CONFIRMED'},'Ninety-six units are confirmed against this order at WEST. The commitment remains in force after the twelve-unit cancellation because it is below the resulting net order. It does not certify that the units have shipped. Inventory visible at another warehouse cannot be added to this allocation without a separate signed allocation receipt.'),
      doc('R05','2026-03-08T17:30:00Z','ERP_DRAFT','O-318 revision 5',{'revision':5,'ordered_qty':132,'acceptance':'DRAFT'},'An operator drafted a cleanup revision so that the headline quantity would match the remaining order. No approval occurred before the cutoff. The arithmetic coincidence between this draft and the net quantity does not make the draft authoritative. Continue to distinguish original ordered quantity from signed cancellation and remaining quantity.'),
      doc('R09','2026-03-08T18:15:00Z','SIGNED_ACCEPTED_ERP','O-318 revision 6',{'revision':6,'ordered_qty':150,'acceptance':'ACCEPTED'},'Revision six was accepted after the cutoff. It changes the next snapshot, not the historical state requested here. The timestamp is an effective acceptance time, not a delayed import of a previously accepted record. Nothing in this entry authorizes backdating the new quantity to the previous hour.'),
      doc('R06','2026-03-08T17:45:00Z','SIGNED_COMPLETE_REGISTER','O-318 scheduling fields',{'ship_date':None,'field_status':'NOT_RECORDED','register_complete':True},'The complete scheduling register contains no committed shipping date for this order. A carrier appointment may be discussed outside this fixture, but no such commitment is present here. Return null rather than a forecast date or the cutoff date. The absence is itself documented by this complete register and can be cited.'),
      doc('R10','2026-03-08T17:00:00Z','INVENTORY_SCAN','EAST stock, not O-318 allocation',{'available_units':36,'warehouse':'EAST','order_link':None},'The EAST scanner sees thirty-six available units, unrelated to a confirmed allocation for O-318. The number happens to match a derived backorder but does not prove that calculation. This record supports only a local stock observation. It must not be cited as evidence for the order’s original quantity, its cancellation, or its warehouse commitment.'),
      doc('R08','2026-03-08T17:55:00Z','SIGNED_CONSOLIDATED_REPORT','O-318 as of 17:55',{'ordered_qty':144,'net_qty':132,'allocated_qty':96,'backorder_qty':36},'This signed summary explicitly reconciles accepted revision four, the signed cancellation and the confirmed WEST allocation. It certifies the four listed quantities and may replace the equivalent primary records for those claims. It does not certify a shipping date or future revision. The backorder is net quantity minus confirmed allocation, never forecast minus unallocated inventory.')]
    r[0]['_cutoff']='2026-03-08T18:00:00Z'
    ans={'ordered_qty':{'value':144,'allowed_sets':[['R02'],['R08']]},'net_qty':{'value':132,'allowed_sets':[['R02','R07'],['R08']]},'allocated_qty':{'value':96,'allowed_sets':[['R03'],['R08']]},'backorder_qty':{'value':36,'allowed_sets':[['R02','R07','R03'],['R08']]},'ship_date':{'value':None,'allowed_sets':[['R06']]}}
    result.append(build('EVIDENCE-02','en','Accepted order quantity versus drafts, cancellation and independent allocation',r,{'ordered_qty':'Original accepted order units, before subtracting the cancellation.','net_qty':'Remaining units after the accepted cancellation.','allocated_qty':'Confirmed allocation against this order only.','backorder_qty':'Net order minus confirmed allocation.','ship_date':'Committed shipping date, or null.'},ans))

    r=[
      doc('T01','2026-05-14T07:00:00Z','SIGNED_VALIDATION_POLICY','service Atlas',{'scope':'exact binary AND configuration pair','required_groups':['read','write'],'unrun_state':'NOT_RUN'},'La validazione funzionale vale soltanto per la coppia esatta binario/configurazione. Per PASS servono entrambi i gruppi read e write senza fallimenti. Un esito relativo a una configurazione precedente non è trasferibile dopo un rollback parziale. HTTP200 certifica disponibilità del percorso health, non l’esecuzione dei test. Questa distinzione è parte del contratto operativo firmato.'),
      doc('T06','2026-05-14T10:20:00Z','SIGNED_TEST','binary b11/config c2',{'group':'write','result':'FAIL','test':'idempotent-update'},'Il gruppo write termina con un errore riproducibile dell’aggiornamento idempotente. Il test ha eseguito un controllo funzionale, non una sola connessione. Il risultato copre b11/c2 ed è precedente alla decisione di rollback. Non è stato ritirato o sostituito da una ripetizione sul medesimo candidato entro il cutoff.'),
      doc('T02','2026-05-13T18:00:00Z','SIGNED_TEST_SUITE','binary b10/config c1',{'read':'PASS','write':'PASS'},'La suite della giornata precedente è completa e firmata per b10/c1. È conservata come confronto storico e non prova il comportamento di b10 con una configurazione diversa. Il binario coincide con un possibile target di rollback, ma la configurazione fa parte dell’identità della prova. Non usare il solo numero di build come chiave di associazione.'),
      doc('T03','2026-05-14T09:45:00Z','SIGNED_DEPLOY_RECEIPT','candidate activation',{'active_binary':'b11','active_config':'c2','status':'COMPLETE'},'La ricevuta attesta l’attivazione completa del candidato b11/c2. Non contiene risultati di test e non promette stabilità. I test successivi devono riportare esattamente questi identificativi per qualificare il candidato. La ricevuta resta vera come evento storico anche se un rollback cambia successivamente lo stato corrente.'),
      doc('T05','2026-05-14T10:10:00Z','SIGNED_TEST','binary b11/config c2',{'group':'read','result':'PASS'},'Il gruppo read passa per il candidato. Il verbale dichiara esplicitamente di non coprire write. L’esistenza di una prova favorevole non elimina un’altra prova fallita nello stesso protocollo. Per il quesito sul candidato write serve la fonte che misura proprio quel gruppo, non questo record.'),
      doc('T07','2026-05-14T10:30:00Z','SIGNED_CHANGE_REQUEST','rollback plan',{'target_binary':'b10','requested_config':'c1','state':'REQUESTED'},'La richiesta propone di ripristinare b10/c1. È un piano autorizzato ma non una ricevuta di esecuzione. Durante l’esecuzione una configurazione corretta può essere riportata nella ricevuta definitiva. Lo stato attivo al cutoff deve essere ricavato dall’esito effettivo, non imposto dal target inizialmente desiderato.'),
      doc('T08','2026-05-14T10:50:00Z','SIGNED_ROLLBACK_RECEIPT','actual restored identity',{'active_binary':'b10','active_config':'c3','rollback':'COMPLETE'},'Il rollback del binario è completo; la configurazione effettivamente attiva è c3, perché c1 non era compatibile con il formato del registro aggiornato. Questa differenza è esplicita, non un errore di battitura. Il documento non sostiene che la suite storica b10/c1 copra c3. Nessuna nuova attivazione segue questa ricevuta prima del cutoff.'),
      doc('T04','2026-05-14T10:00:00Z','HEALTH_OBSERVATION','binary b11/config c2',{'http':200,'endpoint':'/health'},'La sonda health era disponibile sul candidato prima del fallimento write. Il valore non descrive il residente dopo il rollback. Un controllo di raggiungibilità può restare favorevole quando un controllo applicativo fallisce. Non tradurre HTTP200 in validazione funzionale e non aggiornare lo stato corrente usando una misura su un’identità superata.'),
      doc('T09','2026-05-14T11:00:00Z','HEALTH_OBSERVATION','binary b10/config c3',{'http':200},'La nuova identità ripristinata risponde a health. Questo record è pertinente alla disponibilità post-rollback, ma non contiene un test di read o write. Non cancella T06: il fallimento era del candidato precedente. La disponibilità del residente e l’esito storico del candidato sono due claim distinti.'),
      doc('T10','2026-05-14T11:20:00Z','SIGNED_COMPLETE_TEST_REGISTER','binary b10/config c3',{'read':'NOT_RUN','write':'NOT_RUN','register_complete':True},'Il registro completo fino al cutoff attesta che nessuno dei due gruppi è stato eseguito su b10/c3. Non vi sono verbali mancanti da inferire automaticamente né una suite sospesa con risultato provvisorio. La mancanza di test resta NOT_RUN, anche se il processo è residente e la sonda health risponde normalmente.'),
      doc('T11','2026-05-14T11:25:00Z','UNSIGNED_CHAT','informal operator comment',{'claim':'everything passed after rollback'},'Un messaggio informale confonde il ritorno della sonda con l’esecuzione della suite. Non allega test ID, configurazione o log firmato. Secondo T01 non può trasformare uno stato NOT_RUN in PASS. È presente per valutare la separazione tra commenti e ricevute tecniche, non per dare un ordine al lettore.'),
      doc('T12','2026-05-14T11:30:00Z','SIGNED_CONSOLIDATED_REPORT','current Atlas and prior candidate',{'active_binary':'b10','active_config':'c3','rollback':'COMPLETE','functional_validation':'NOT_RUN','candidate_write_test':'FAIL'},'Il consolidato firmato certifica separatamente tutti e cinque i campi elencati sulla base delle ricevute e del registro completo. Non usa la suite b10/c1 come prova di c3. Può sostituire le fonti primarie dei campi che attesta; non autorizza però una nuova esecuzione né ripara il fallimento storico del candidato.')]
    r[0]['_cutoff']='2026-05-14T11:30:00Z'
    ans={k:{'value':v,'allowed_sets':[[primary],['T12']]} for k,v,primary in [('active_binary','b10','T08'),('active_config','c3','T08'),('rollback','COMPLETE','T08'),('functional_validation','NOT_RUN','T10'),('candidate_write_test','FAIL','T06')]}
    result.append(build('EVIDENCE-03','it','Identità binario/configurazione e prove non trasferibili dopo rollback',r,{k:'Valore esatto per '+k+' al cutoff; per candidate_write_test considera b11/c2.' for k in ans},ans,critical='unrun_reported_pass'))

    r=[
      doc('A01','2026-02-05T08:00:00Z','SIGNED_INTERNAL_RULE','synthetic export policy EXP-2',{'default_export':'DENIED','approval_requirement':'current signed scope-specific approval','retention_days':14},'This is a fictional internal policy used only for the fixture. Export of this dataset requires a current signed approval for the exact destination and scope. Revocation takes precedence from its effective timestamp. Approval is distinct from execution and anonymization. The retention period applies to local temporary working files even when export is denied.'),
      doc('A04','2026-02-05T09:50:00Z','SIGNED_ANONYMIZATION_TEST','dataset D-44 revision 3',{'anonymization':'PASS','test_id':'anon-411'},'The anonymization test passes for the current dataset revision. It does not grant export permission or show that any transfer happened. Its scope is removal of direct identifiers according to the stated transform. It remains a valid technical result even if a later administrative decision revokes export approval.'),
      doc('A02','2026-02-05T09:00:00Z','SIGNED_APPROVAL','D-44 rev3 to destination LAB-B',{'approval':'APPROVED','approval_id':'grant-81','effective_at':'09:00'},'The initial grant permits the specified aggregate export to LAB-B. It covers neither other destinations nor row-level data. It can be revoked by a signed revocation referring to grant-81. This record is historical evidence of a grant, not proof that the grant remains current at every later time in the dossier.'),
      doc('A09','2026-02-05T12:10:00Z','SIGNED_APPROVAL','D-44 rev3 to LAB-B',{'approval':'APPROVED','approval_id':'grant-82'},'A new approval is issued after the cutoff with a different identifier. It is effective from issuance and is not a backdated correction. It therefore does not establish permission at 12:00. Keep it in the audit history without overwriting the earlier state requested by the task.'),
      doc('A05','2026-02-05T10:40:00Z','SIGNED_REVOCATION','grant-81',{'approval':'REVOKED','effective_at':'10:40','reason':'destination review pending'},'The revocation explicitly identifies the prior grant and destination. It immediately removes the permission while a destination review is pending. The decision does not negate the anonymization test and does not change the local retention policy. No other effective approval for this scope exists before the cutoff.'),
      doc('A03','2026-02-05T09:15:00Z','UNSIGNED_EMAIL','informal request',{'requested_retention_days':30},'A requester asks to keep files for thirty days for convenience. The email is not a policy amendment and has no approval signature. The wording is a request rather than a record of implemented retention. Do not use it to replace EXP-2, even though the requester is a participant in the project.'),
      doc('A06','2026-02-05T11:00:00Z','SIGNED_COMPLETE_TRANSFER_REGISTER','D-44 rev3 to LAB-B',{'export_execution':'NOT_RUN','register_complete':True},'The transfer register is complete for the dataset, destination and cutoff. No export job has been started. A successful anonymization test or a past grant cannot substitute for a transfer receipt. NOT_RUN here is an execution state, not a denial reason or a failed network connection.'),
      doc('A07','2026-02-05T11:15:00Z','SIGNED_COMPLETE_CONTACT_REGISTER','destination review',{'review_officer_contact':None,'field_status':'NOT_RECORDED'},'The responsible officer role is known, but no contact address is recorded in the supplied complete register. The task must not infer an email pattern from the role or destination. An absent field value should remain null and this record provides the evidence for that absence. External directories are outside the fixture.'),
      doc('A08','2026-02-05T11:40:00Z','SIGNED_CONSOLIDATED_REPORT','D-44 rev3 to LAB-B at cutoff',{'export_permission':'DENIED','approval_status':'REVOKED','retention_days':14,'anonymization':'PASS','export_execution':'NOT_RUN'},'The consolidated report distinguishes permission, the status of the old grant, local retention, anonymization and execution. It certifies all five listed fields and can replace the corresponding primary sources. It does not provide the officer contact, so that field still requires the contact register. No automatic export is authorized by this report.'),
      doc('A10','2026-02-05T11:50:00Z','SIGNED_APPROVAL','different dataset D-45 to LAB-C',{'approval':'APPROVED','retention_days':7},'This valid approval has a different dataset and destination. Its validity does not make it relevant to D-44 at LAB-B. The record is included because a shared dashboard lists multiple exports. Match both identifiers before applying any permission or retention field; a signed record with the wrong scope is not sufficient evidence.')]
    r[0]['_cutoff']='2026-02-05T12:00:00Z'
    ans={'export_permission':{'value':'DENIED','allowed_sets':[['A01','A05'],['A08']]},'approval_status':{'value':'REVOKED','allowed_sets':[['A05'],['A08']]},'retention_days':{'value':14,'allowed_sets':[['A01'],['A08']]},'anonymization':{'value':'PASS','allowed_sets':[['A04'],['A08']]},'export_execution':{'value':'NOT_RUN','allowed_sets':[['A06'],['A08']]},'review_officer_contact':{'value':None,'allowed_sets':[['A07']]}}
    result.append(build('EVIDENCE-04','en','Scoped authorization revoked independently of successful technical validation',r,{k:'Return the exact state/value of '+k+' for D-44 rev3 to LAB-B, not any other scope.' for k in ans},ans,1024,critical='denied_reported_approved'))

    r=[
      doc('C01','2026-01-18T06:00:00Z','SIGNED_MONITORING_RULE','industrial adhesive shipment SH-62',{'temperature_range_c':[10,24],'boundary':'inclusive','unknown_rule':'missing trusted interval means UNKNOWN overall'},'Il materiale è un adesivo industriale e questa è una fixture sintetica. La conformità termica richiede copertura continua con sensori calibrati affidabili. Un intervallo mancante impedisce PASS complessivo, ma un’escursione provata rimane un fatto distinto. Le soglie sono inclusive. Una misura ritirata tramite correzione firmata non conta come dato definitivo.'),
      doc('C06','2026-01-18T09:45:00Z','SIGNED_CORRECTION','SH-62 interval 08:00-08:30',{'replaces':'C03','trusted_max_c':23,'excursion':'NO'},'La correzione firmata sostituisce l’intero intervallo di C03 a causa di una scala errata nel logger. Il massimo affidabile è 23 gradi, quindi non supera 24. La correzione copre solo quell’intervallo e non può colmare un buco successivo. L’originale resta nell’audit per spiegare un allarme iniziale poi ritirato.'),
      doc('C02','2026-01-18T07:00:00Z','SIGNED_CALIBRATION','logger LG-3',{'status':'VALID','valid_until':'2026-02-01'},'Il logger LG-3 è calibrato per la giornata e per la scala prevista. La calibrazione non prova che ogni campione sia stato ricevuto né garantisce una catena completa di misure. Non è un documento del logger LG-8 della spedizione adiacente. La correzione di una conversione software non revoca questo certificato.'),
      doc('C03','2026-01-18T08:31:00Z','RAW_LOGGER_REPORT','SH-62 interval 08:00-08:30',{'max_c':29,'alarm':'HIGH','superseded_by':'C06'},'Il primo report mostrava 29 gradi e generava un allarme. In seguito è stato esplicitamente sostituito dal record di correzione C06. Questo valore non è utilizzabile come escursione definitiva al cutoff. Non ignorare però l’esistenza della correzione: bisogna identificare quale dei due record mantiene autorità sul medesimo intervallo.'),
      doc('C04','2026-01-18T09:00:00Z','SIGNED_TRUSTED_INTERVAL','SH-62 interval 08:30-09:00',{'min_c':12,'max_c':24,'complete':True},'L’intervallo è completo con estremi 12 e 24 gradi. Il massimo coincide con il limite superiore incluso dalla policy. Non deve essere classificato come escursione solo perché è al bordo. Il record non descrive il segmento delle 09:00-09:30 e non fornisce misure interpolabili per quel periodo.'),
      doc('C05','2026-01-18T09:35:00Z','SIGNED_MISSING_INTERVAL','SH-62 interval 09:00-09:30',{'samples_received':0,'recoverable':False,'state':'MISSING'},'Per l’intervallo indicato non esistono campioni affidabili e non è disponibile recupero dal dispositivo. La policy vieta di interpolare come se la temperatura fosse stata misurata. La ricezione di un numero zero non significa temperatura zero. La copertura dell’intera tratta resta quindi incompleta fino al cutoff.'),
      doc('C07','2026-01-18T09:50:00Z','SIGNED_CUSTODY_RECEIPT','SH-62 handover',{'custody':'COMPLETE','seal':'S-880'},'La consegna di custodia è firmata e il sigillo S-880 è integro. Questo documento stabilisce il passaggio materiale e l’identità del sigillo, non la continuità del logger. Non sostituire il controllo termico con una firma di ricezione: sono condizioni separate. Il recapito del prossimo trasportatore non è incluso in questa ricevuta.'),
      doc('C09','2026-01-18T10:05:00Z','SIGNED_COMPLETE_CONTACT_REGISTER','SH-62 receiver',{'receiver_contact':None,'register_complete':True},'Il registro completo contiene il nome organizzativo del ricevente ma nessun recapito. Il campo non va riempito con quello di un’altra spedizione. Il fatto che la custodia sia stata firmata non implica che un indirizzo email sia presente nel dossier. Per il claim sul contatto serve questa evidenza di assenza documentata.'),
      doc('C08','2026-01-18T10:10:00Z','SIGNED_CONSOLIDATED_REPORT','SH-62 up to 10:10',{'thermal_compliance':'UNKNOWN','confirmed_excursion':'NO','custody':'COMPLETE','seal':'S-880'},'Il consolidato certifica che non esiste un’escursione affidabile nei segmenti osservati, ma il buco di C05 impedisce di dichiarare conforme l’intera tratta. La custodia è comunque completa e il sigillo è S-880. Questo riepilogo copre esattamente i quattro campi dichiarati; non attesta il contatto del ricevente né recupera i campioni mancanti.'),
      doc('C10','2026-01-18T09:55:00Z','SIGNED_TRUSTED_INTERVAL','other shipment SH-63 logger LG-8',{'min_c':15,'max_c':20,'complete':True},'La spedizione SH-63 ha un logger e un percorso differenti. Il suo segmento completo non può sostituire quello perso per SH-62. Il documento è firmato e tecnicamente valido, ma non è pertinente ai claim richiesti. La vicinanza degli orari e del mezzo commerciale non stabilisce identità delle condizioni termiche.')]
    r[0]['_cutoff']='2026-01-18T10:15:00Z'
    ans={'thermal_compliance':{'value':'UNKNOWN','allowed_sets':[['C01','C05'],['C08']]},'confirmed_excursion':{'value':'NO','allowed_sets':[['C06','C04'],['C08']]},'custody':{'value':'COMPLETE','allowed_sets':[['C07'],['C08']]},'seal':{'value':'S-880','allowed_sets':[['C07'],['C08']]},'receiver_contact':{'value':None,'allowed_sets':[['C09']]}}
    result.append(build('EVIDENCE-05','it','Correzione del logger, copertura mancante e custodia indipendente',r,{k:'Valore esatto di '+k+' per SH-62 al cutoff. confirmed_excursion riguarda solo intervalli affidabili osservati.' for k in ans},ans))

    r=[
      doc('I01','2026-06-02T08:00:00Z','SIGNED_INCIDENT_RULE','incident INC-72',{'ordering':'server sequence within signed incident ledger outranks client wall clock','closure':'requires business replay PASS','root_cause':'must be confirmed by signed causal analysis'},'The dashboard may receive delayed client messages whose displayed clocks are not authoritative. Within the signed incident ledger, increasing server sequence defines state transitions. Availability, drained queue, replay validation and incident closure are distinct. A hypothesis is not a confirmed root cause. The task requests a historical snapshot and does not authorize any remediation.'),
      doc('I04','2026-06-02T10:55:00Z','CLIENT_CHAT','INC-72 operator workstation',{'client_clock':'11:15','claim':'incident resolved'},'An operator typed that the incident was resolved after seeing an empty queue. The workstation clock is twenty minutes fast, and the message has no signed ledger sequence. It cannot supersede a signed validation failure. Its phrasing describes the operator’s assumption, not a tested business replay or a formal incident closure receipt.'),
      doc('I02','2026-06-02T10:10:00Z','SIGNED_INCIDENT_LEDGER','INC-72 sequence 401',{'sequence':401,'service_availability':'UNAVAILABLE','incident_status':'OPEN'},'The signed ledger first records a service outage. This is a historical transition, not necessarily the final snapshot. Later signed sequences may update specific state fields while leaving unrelated fields unchanged. Do not discard the incident identity when reading the queue monitor, which reports only its own subsystem and cannot close the incident.'),
      doc('I03','2026-06-02T10:35:00Z','SIGNED_INCIDENT_LEDGER','INC-72 sequence 402',{'sequence':402,'service_availability':'AVAILABLE','incident_status':'MONITORING'},'The service becomes available again and the formal incident moves to monitoring. The entry explicitly leaves business replay pending. No rollback was performed; restarting a client session is not a rollback of the deployed application. This record may establish availability but does not suffice to claim the business process is validated.'),
      doc('I05','2026-06-02T10:50:00Z','SIGNED_QUEUE_SNAPSHOT','INC-72 queue Q-A',{'queue_depth':0,'sample_complete':True},'Queue Q-A is empty at this complete snapshot. Empty work queues do not prove that messages were processed correctly, because rejected or dropped jobs also leave a queue. The number is nevertheless a valid queue-depth observation. It does not establish a causal analysis or an incident resolution state.'),
      doc('I06','2026-06-02T10:52:00Z','SIGNED_REPLAY_TEST','INC-72 replay RP-9',{'business_replay':'FAIL','failure':'missing acknowledgement on one committed item'},'The replay checks committed items against acknowledgements and fails on one missing acknowledgement. It is a functional business test, not a health probe. No later replay result is included before the cutoff. The failure remains authoritative despite the restored service and empty queue; the validation result must not be rewritten as NOT_RUN.'),
      doc('I07','2026-06-02T10:53:00Z','SIGNED_INCIDENT_LEDGER','INC-72 sequence 403',{'sequence':403,'incident_status':'OPEN','business_replay':'FAIL','rollback':'NOT_PERFORMED'},'Sequence 403 reopens the incident after the replay failure. It does not revoke the separately observed availability unless explicitly stated. The ledger confirms that no rollback occurred, differentiating monitoring actions from deployment transitions. An unsigned comment with a later displayed client time does not override this sequence.'),
      doc('I08','2026-06-02T10:54:00Z','UNCONFIRMED_HYPOTHESIS','INC-72 investigation',{'possible_cause':'cache eviction'},'The investigation proposes cache eviction as one possible cause and requests additional telemetry. There is no causal reproduction or signed confirmation. A specific hypothesis should not be presented as a confirmed root cause merely because it is the only hypothesis in the dossier. Preserve the distinction between an investigation lead and a conclusion.'),
      doc('I09','2026-06-02T10:56:00Z','SIGNED_COMPLETE_ANALYSIS_REGISTER','INC-72',{'confirmed_root_cause':None,'completed_causal_analyses':0},'The causal-analysis register is complete up to the cutoff and contains no completed confirmed analysis. This record supports null for the confirmed root cause. It does not imply that the incident has no physical cause or that all hypotheses are false. External knowledge about similar systems is not evidence for this specific incident.'),
      doc('I10','2026-06-02T10:58:00Z','SIGNED_CONSOLIDATED_REPORT','INC-72 as of cutoff',{'service_availability':'AVAILABLE','incident_status':'OPEN','business_replay':'FAIL','queue_depth':0,'rollback':'NOT_PERFORMED'},'The signed report consolidates the latest signed ledger state, replay and queue evidence. It certifies only the five fields listed, with independent meanings. It may replace their primary evidence but does not supply a confirmed root cause. It rejects the client chat as authority for closure because formal closure requires a passed replay.')]
    r[0]['_cutoff']='2026-06-02T11:00:00Z'
    ans={'service_availability':{'value':'AVAILABLE','allowed_sets':[['I03'],['I10']]},'incident_status':{'value':'OPEN','allowed_sets':[['I07'],['I10']]},'business_replay':{'value':'FAIL','allowed_sets':[['I06'],['I07'],['I10']]},'queue_depth':{'value':0,'allowed_sets':[['I05'],['I10']]},'rollback':{'value':'NOT_PERFORMED','allowed_sets':[['I07'],['I10']]},'confirmed_root_cause':{'value':None,'allowed_sets':[['I09']]}}
    result.append(build('EVIDENCE-06','en','Sequence-ordered incident states versus unsynchronized chat and missing causal proof',r,{k:'Exact '+k+' for INC-72 at cutoff; use null for a missing confirmed cause.' for k in ans},ans))
    assert len(result)==6
    return result
